### ISSUE TITLE
Displayed vouchers not network aware (?)

### ISSUE THREAD

**Issue by WietseWind** [technotip/voucher-issues#3]
Opened the xApp at mainnet, saw the vouchers from my previous testnet sessions.

1. Create voucher @ testnet
2. Am at mainnet
3. Same vouchers visible

**Comment by technotip** [comment]
No it's not network aware. The xApp will **only** work on **Xahau Mainnet** anyway.
Only our team tested it on testnet, so we can remove those testnet vouchers. It won't be a problem for anyone else.
