### ISSUE TITLE
Create custom amount voucher: improvements

### ISSUE THREAD

**Issue by WietseWind** [technotip/voucher-issues#4]
For creation of custom amount vouchers:

1. On tap choose custom amount: auto focus in text input
2. Show boundaries @ custom amounts (min, max, max within limit)

**Comment by technotip** [comment]
1. Auto focus doesn't work with webviews. I'll check with some js libraries, if we can enable this somehow.
2. Right now we have alert messages when user tries to enter below min or above max allowed values for the voucher. We also have the min, max and cap details on the main screen itself.

Maybe we can display the same message below the "Create voucher" button, in the popup modal?


![WhatsApp Image 2024-06-02 at 12 22 47 PM (1)](https://github.com/technotip/voucher-issues/assets/4805549/cb825b0a-fe8a-4847-8184-231b4eac0f31)
![WhatsApp Image 2024-06-02 at 12 22 47 PM](https://github.com/technotip/voucher-issues/assets/4805549/0d4dab9a-71ed-4665-b63e-48791eeb43ef)

**Comment by WietseWind** [comment]
@technotip And what with a manual focus? `document.getElementById('..').focus()` should be a method. If vue/virtual dom, obviously in the next tick.

**Comment by technotip** [comment]
> @technotip And what with a manual focus? `document.getElementById('..').focus()` should be a method. If vue/virtual dom, obviously in the next tick.

Thank you ..fixed.
